config/routes.rb
Rails.application.routes.draw do      
  scope '(:locale)', locale: /en|ja/ do
    resources :users, :applicants, :religions, :countries, :job_types, :projects, :job_orders, :file_types, :academic_abilities, :aptitude_tests, :pww_logos
    
    # AJAX REQUESTS
    ## Religions
    get 'get_all_religions' => 'religions#get_all_religions'
    get 'add_new_religion' => 'religions#add_new_religion'
    post 'edit_religion' => 'religions#edit_religion'
    get 'delete_religion' => 'religions#delete_religion'

    ## Job Types
    get 'get_all_job_types' => 'job_types#get_all_job_types'
    get 'add_new_job_type' => 'job_types#add_new_job_type'
    post 'edit_job_type' => 'job_types#edit_job_type'
    get 'delete_job_type' => 'job_types#delete_job_type'

    ## Countries
    get 'get_all_countries' => 'countries#get_all_countries'
    get 'add_new_country' => 'countries#add_new_country'
    post 'edit_country' => 'countries#edit_country'
    get 'delete_country' => 'countries#delete_country'

    ## Projects
    get 'get_all_projects' => 'projects#get_all_projects'
    get 'add_new_project' => 'projects#add_new_project'
    get 'delete_project' => 'projects#delete_project'
    get 'project_remove_document' => 'projects#project_remove_document'
    get 'view_project_applicants' => 'projects#view_project_applicants'
    post 'send_email_job_order' => 'projects#send_email_job_order'
    get 'project_chart' => 'home#project_chart'
    get 'get_last_sent_mail_date' => 'projects#get_last_sent_mail_date'

    ## Users
    get 'delete_user_account' => 'users#destroy'
    get 'delete_applicant' => 'applicants#destroy'

    ## File Type
    get 'get_all_file_types' => 'file_types#get_all_file_types'
    get 'add_new_file_type' => 'file_types#add_new_file_type'
    post 'edit_file_type' => 'file_types#edit_file_type'
    get 'delete_file_type' => 'file_types#delete_file_type'

    ## Academic Abilities
    get 'get_all_academic_abilities' => 'academic_abilities#get_all_academic_abilities'
    get 'add_new_academic_ability' => 'academic_abilities#add_new_academic_ability'
    post 'edit_academic_ability' => 'academic_abilities#edit_academic_ability'
    get 'delete_academic_ability' => 'academic_abilities#delete_academic_ability'

    ## Aptitude Tests
    get 'get_all_aptitude_tests' => 'aptitude_tests#get_all_aptitude_tests'
    get 'add_new_aptitude_test' => 'aptitude_tests#add_new_aptitude_test'
    post 'edit_aptitude_test' => 'aptitude_tests#edit_aptitude_test'
    get 'delete_aptitude_test' => 'aptitude_tests#delete_aptitude_test'

    ## Applicant Files
    get 'applicant_files' => 'applicant_files#index'
    get 'delete_applicant_file' => 'applicant_files#destroy'

    ## Search
    get 'search' => 'search#index'
    get 'quick_search' => 'search#quick_search', as: 'quick_search'
    post 'search_applicants' => 'search#search_applicants', as: 'search_applicants'    

    ## Applicants
    get 'lock_function' => 'applicants#lock_function'
    get 'video_interview' => 'applicants#video_interview'
    get 'video_self_introduction' => 'applicants#video_self_introduction'    
    get 'project_history' => 'applicants#project_history'
    get 'requests_for_applicant_record_deletion' => 'applicants#to_be_deleted'
    get 'request_for_delete_applicant' => 'applicants#request_for_delete_applicant'
    get 'restore_applicant' => 'applicants#restore_applicant'
    get 'make_comments_to_applicant' => 'applicants#make_comments_to_applicant'

    # PWW Logo
    get 'delete_pww_logo' => 'pww_logos#destroy'

    ## Generate PDF Reports
    get 'generate_applicant_report' => 'applicants#generate_applicant_report', as: 'generate_applicant_report'
    match 'generate_pdf_full_report' => 'search#generate_pdf_full_report', via: :get
    match 'generate_csv_full_report' => 'search#generate_csv_full_report', as: 'generate_csv_full_report', via: :get

    ## Authenticate Admin Password Before Record Deletion
    post 'authenticate_user_password' => 'users#authenticate_user_password'

    ## User Auth Functions    
    controller :login do
        get 'login' => :index, as: :login
        post 'authenticate_login' => :authenticate_login
        get 'logout' => :destroy
        # delete 'logout' => 'login#destroy'
    end
    
    mount Ckeditor::Engine => '/ckeditor'
    match 'home' => 'home#index', via: :get, as: 'home'
    root :to => 'login#index'
  end

  match '*path', :to => 'application#render_404', :via => :all, :locale => 'en' # render 404 page when routes not found
  match '/*locale/*path', to: redirect('/#{I18n.default_locale}/%{path}'), :via => :get # handles /bad-locale|anything/valid-path
  match '/*path', to: redirect('/#{I18n.default_locale}/%{path}'), :via => :get # handles /anything|valid-path-but-no-locale  
end

app/models/user.rb
# Email format validator class
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is invalid format")
    end
  end
end

class User < ActiveRecord::Base
  require 'iconv'
  has_many :client_projects, class_name: 'Project', :foreign_key => 'client_id'
  has_many :partner_projects, class_name: 'Project', :foreign_key => 'partner_id'
  has_many :applicants, through: :client_projects
  has_many :partner_created_applicants, class_name: 'Applicant', foreign_key: :creator_id
  belongs_to :pww_logo

  # get Admins user
  scope :admins, -> { where(role: 'admin').order('fullname asc') }
  # get Partners user
  scope :partners, -> { where(role: 'partner').order('fullname asc') }
  # get Clients user
  scope :clients, -> { where(role: 'client').order('fullname asc') }

  # calls set_downcase_email & set_downcase_role method before save
  before_save :set_downcase_email, :set_downcase_role
  
  validates_presence_of :fullname, :username, :pww_logo_id
  validates :fullname, uniqueness: { case_sensitive: false }
  validates :username, uniqueness: { case_sensitive: false }
  validates :password, :length => { minimum: 6, message: 'is too short.' }, on: :create
  validates :email, presence: true, email: true

  has_secure_password

  Roles = [ :admin , :client, :partner ]

  def role?( requested_role )
    self.role == requested_role.to_s
  end

  # set email to lower case before save
  def set_downcase_email
    self.email = email.downcase if email.present?    
  end

  # set user role to lower case before save
  def set_downcase_role
    self.role = role.downcase if role.present?
  end

  def admin_pww_logo
    self.pww_logo_id
  end
     
  has_attached_file :image, :styles => {mini: '30x30', thumb: '80x80>' # is for cropping
  },
  :url  => "/images/users/:id/:style/:basename.:extension",
  :path => ":rails_root/public/images/users/:id/:style/:basename.:extension",
  :default_url => '/assets/default_avatar.jpg',
  :default_style => :thumb
  
  # validates attachment file, should be an image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
  # validates_attachment :avatar, :presence => true,
  # :content_type => { :content_type => "image/jpeg" },
  # :size => { :in => 0..10.kilobytes }
  
  before_post_process :transliterate_file_name
  
  def transliterate_file_name
    extension = File.extname(image.original_filename).gsub(/^\.+/, '')
    filename = image.original_filename.gsub(/\.#{extension}$/, '')
    self.image.instance_write(:file_name, "#{transliterate(filename)}.#{transliterate(extension)}")
  end
  
  def transliterate(str)
    s = Iconv.iconv('ascii//ignore//translit', 'utf-8', str).to_s
    s.downcase!
    s.gsub!(/'/, '')
    s.gsub!(/[^A-Za-z0-9]+/, ' ')
    s.strip!
    s.gsub!(/\ +/, '-')
    return s
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource except: [:authenticate_user_password]

  layout 'cms'
  include CheckLoginModule
  before_action :check_login
  before_action :get_pww_logos, only: [:new, :create, :edit, :update]

  # Note: Since I'm using load_and_authorize_resource function, it will do:
  # @users = User.all
  # @user = User.new
  # @user = User.create(user_params)
  # @user = User.find(params[:id])

  def index
    @page_title = 'User Accounts List'    
  end

  def show
    render action: 'index'
  end
  
  def new
    @page_title = 'New User Account'
  end
  
  def create
    @page_title = 'New User Account'
    @user.last_updated_by = session[:username]
    if @user.save
      flash.keep[:status] = 'success'
      flash.keep[:notice] = 'New user account was successfully created.'
      redirect_to users_path(:locale => I18n.locale)
    else
      flash.keep[:status] = 'error'
      flash.keep[:notice] = 'Sorry, there was an error saving.'
      @menu = 'users'
      render action: 'new'
    end
  end
  
  def edit
    @menu = 'users'
    @page_title = 'Edit User Account'
  end
  
  def update
    @user.last_updated_by = session[:username]
    if @user.update_attributes(user_params)   #user_params.reject{|k,v| v.blank?}            
      flash[:status] = 'success'
      flash[:notice] = "#{@user.username.capitalize} information was successfully updated."
      
      redirect_to users_path(:locale => I18n.locale)
    else
      @menu = 'users'
      @page_title = 'Edit User Account'
      flash[:status] = 'error'
      flash[:notice] = 'Sorry, there was an error updating.'
      
      render action: 'edit'
    end
  end
  
  def destroy
    unless @user.nil?
      @user.destroy
      render json: {status: 'success', message: 'You have successfully deleted User Account.'}
    else
      render json: {status: 'error', message: 'Sorry, unable to find User Account.'}
    end    
  end
  
  def delete_profile_image
    @user.last_updated_by = session[:username]
    @user.image_file_name = nil
    @user.image_file_size = nil
    @user.image_content_type = nil
    if @user.save
      render json: {status: 'success', message: 'Profile Image was successfully removed.'}
    else
      render json: {status: 'error', message: 'Unable to remover Profile Image.'}
    end
  end

  def authenticate_user_password
    user = authenticate_current_user(session[:username], params[:password])
    if user
      render json: {status: 'success', message: 'User password was authenticated!'}
    else
      render json: {status: 'error', message: 'Sorry Invalid Password. Please Try Again!'}
    end
  end
    
  private
  def user_params
    params.require(:user).permit!
  end

  def get_pww_logos
    @pww_logos = PwwLogo.active.order('title ASC')
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<input type="hidden" name="locale" value="<%= I18n.locale %>" />
<div align="left" class="form-group">
    <span class="col-md-1 text-center"><i class="fa fa-user bigicon"></i></span>
    <div class="col-md-11">
        <%= f.text_field :fullname, :class => "form-control text-capitalize", :placeholder => "Fullname *", autofocus: true, required: '' %>
    </div>
</div>
    
<div align="left" class="form-group">
    <span class="col-md-1 text-center"><i class="fa fa-users bigicon"></i></span>
    <div class="col-md-11">
        <%= f.text_field :username, :class => "form-control", :placeholder => "Username *", :autocomplete => "off", required: '' %>
    </div>
</div>

<div align="left" class="form-group">
    <span class="col-md-1 text-center"><i class="fa fa-key bigicon"></i></span>
    <div class="col-md-11">
        <%= f.password_field :password, :class => "form-control", :placeholder => "Password (minimum of 6 alphanumeric characters) *", :autocomplete => "off" %>
    </div>
</div>

<div><%= image_tag('icons/pass_gen.jpeg', id: 'open_pass_gen_modal') %></div>

<div align="left" class="form-group">
   <span class="col-md-1 text-center"><i class="fa fa-repeat bigicon"></i></span>
   <div class="col-md-11">
       <%= f.password_field :password_confirmation, placeholder: "Re-Type Password *", class: "form-control", data: {fv_identical: "true", fv_identical_field: "user[password]", fv_identical_message: "The passwords are not the same."} %>
   </div>
</div>

<div align="left" class="form-group">
  <span class="col-md-1 text-center"><i class="fa fa-envelope-o bigicon"></i></span>
  <div class="col-md-11">
    <%= f.text_field :email, :class => "form-control", :placeholder => "Email Address *", required: '' %>
  </div>
</div>

<div align="left" class="form-group">
  <span class="col-md-1 text-center"><i class="fa fa-cogs bigicon"></i></span>
  <div class="col-md-11">
    <%= f.select(:role, [['Administrator Account','admin'], ['Partner Account','partner'], ['Client Account', 'client']], {}, {class: 'form-control'} )%>
  </div>
</div>

<div id="pww_logo_holder" align="left" class="form-group">
  <span class="col-md-1 text-center"><i class="fa fa-bookmark-o bigicon"></i></span>
  <div class="col-md-11">     
    <%= f.select(:pww_logo_id, @pww_logos.collect {|c| [ c.title, c.id ] }, {include_blank: '-select logo for PDF Reports-'}, class: 'form-control', :required => true) %>    
  </div>
</div>

<div align="left" class="form-group">
  <span class="col-md-1 text-center"><i class="fa fa-eye bigicon"></i></span>
  <div class="col-md-11">
    <%= f.select :status, options_for_select([['Activate User Access', true],['Deactivate User Acces',false]], :selected => @user.status), {}, { :class => 'form-control' } %>
  </div>
</div>

<div align="left" class="form-group">                  
  <span class="col-md-1 text-center">
  <% if action == 'new' %>
    <i class="fa fa-picture-o bigicon"></i>
  <% else %>
    <%= image_tag(user_profile_image(@user, 'thumb'), :class => 'round_me') %>
  <% end %>
  </span>
  <div class="col-md-11">
    <input id="user_upload_image" name="user[image]" type="file" class="file" data-preview-file-type="text" data-show-preview="true" data-show-upload="false" data-show-caption="true" />
  </div>
</div>

<div align="left" class="form-group">
  <span class="col-md-1 text-center"><i class="fa fa-phone-square bigicon"></i></span>
  <div class="col-md-11">
     <div class="input-group">
      <span class="input-group-addon input_jp" id="basic-addon1">&nbsp;&nbsp;&nbsp;&nbsp;</span>                  
      <%= f.text_field :phone, :class => "form-control", :maxlength => "20", :placeholder => "Phone Number (optional only)" %>
    </div>
  </div>
</div>

<div align="left" class="form-group">
  <span class="col-md-1 text-center"><i class="fa fa-pencil-square-o bigicon"></i></span>
  <div class="col-md-11">
    <%= f.text_area :description, :class => "form-control ", :placeholder => "Enter user description here (optional only)", :rows => "5" %>
  </div>
</div>

<!-- Save Now Button -->
<div class="col-md-12 pad0">
    <div class="text-right">
      <a href="<%= users_path(locale: I18n.locale) %>" class="btn btn-warning btn-lg long-btn">CANCEL</a>
      <%= f.submit 'SAVE NOW', class: 'btn btn-danger btn-lg long-btn' %>
    </div>
</div> 

app/views/users/_generate_password_modal.html.erb
<div class="modal fade" id="modal_generate_password" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content text-center" style="margin-top: 140px;">            
      <div class="fade in margin_btm30" role="alert">
        <%= image_tag("close.png", class: 'modal_close_btn') %>
        <h2 class="are_you_sure">Generator For Secure Password!</h2>
        <div class="text-center"><b>Copy and paste the generated random texts in password fields.</b></div>
        <div id="gen_pass_wrapper" class="text-center">
          <input type="text" id="generated_random_password" />
        </div>
        <button id="generate_password_btn" class="btn btn-lg btn-danger">Generate Now</button>
        <button id="copy_generated_password" data-clipboard-target="#generated_random_password" data-toggle="popover" data-content="Copied!" class="btn btn-lg btn-warning">Copy</button>
      </div>
    </div>
  </div>
</div>

app/views/users/_listing.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="table-responsive">
      <div class="dataTable_wrapper">
        <table class="table table-striped table-bordered table-hover makeDataTable" id="user_table_<%= account %>">
          <thead>
            <tr>
              <th style="width: 5%;">Profile</th>
              <th style="width: 15%;">Username</th>
              <th style="width: 15%;">Fullname</th>              
              <th style="width: 8%;">Status</th>
              <th style="width: 15%;">Email</th>              
              <th style="width: 15%;" class="text-center">PDF Report Logo</th>
              <th style="width: 12%;">Last Updated By/At</th>
              <th style="width: 15%;" class="text-center">Actions</th>
            </tr>
          </thead>
          <tbody>
            <%
            case account
            when 'admins'
              users = users.admins
            when 'partners'
              users = users.partners
            when 'clients'
              users = users.clients
            end
            %>
            <% users.each do |user| %>
              <tr>
                <td><%= image_tag(user_profile_image(user, 'thumb'), :class => 'height_width50') %></td>
                <td><%= user.username %></td>
                <td class="text-capitalize"><%= user.fullname %></td>                
                <td class="<%= user.status == true ? 'activated' : 'deactivated' %>"><%= user.status == true ? 'Activated' : 'Deactivated' %></td>
                <td><%= !user.email.blank? ? user.email : '-' %></td>      
                <td class="text-center">
                  <b><%= user.try(:pww_logo).try(:title) %></b><br>
                  <%= image_tag user.try(:pww_logo).try(:logo).url(:medium), style: 'max-height: 40px;' if user.pww_logo %>
                </td>
                <td>
                  <strong><%= !user.last_updated_by.blank? ? user.last_updated_by : '-' %></strong>
                  <br><%= user.updated_at.to_time.strftime("%a, %e %b %Y %H:%M") %>
                </td>
                <td class="text-center">
                  <a href="<%= edit_user_path(user, :locale => I18n.locale) %>" class="edit_user"><i class="fa fa-edit list_icon" aria-hidden="true"></i></a>
                  <a href="#" class='delete_user_account' data-id="<%= user.id %>" title="Remove <%= user.username %>"><i class="fa fa-remove list_icon" aria-hidden="true"></i></a>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>          
  </div>
</div>

app/views/users/edit.html.erb
<% content_for :include_styles do %>
  <%= stylesheet_link_tag "fileinput.min.css", media: "all" %>  
<% end %>

<% content_for :include_scripts do %>
  <%= javascript_include_tag "fileinput.min.js" %>
  <%= javascript_include_tag "clipboard.min.js"  %>
  <%= javascript_include_tag "users/generate_password.js" %>  
<% end %>

<% content_for :page_icon do %>
  <i class="fa fa-user custom_icon" aria-hidden="true"></i>
<% end %>

<% content_for :body do %>
<div class="row">  
  <% if @user.errors.any? %>
    <div class="alert alert-danger custom_alert_notification">
      <button id="error_alert_x" type="button" class="close"><span aria-hidden="true">&times;</span></button>
      <strong>There was <%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</strong>
      <div id="errorExplanation">      
          <% @user.errors.full_messages.each do |msg| %>
          <p style="display: inline;">* <%= msg %></p><br />
          <% end %>
      </div>
    </div> 
  <% end %>

  <%= render partial: 'users/generate_password_modal' %>

  <%= form_for(@user, :url => user_path(@user, :locale => I18n.locale), :html => {:class => "form-horizontal", :multipart => true}) do |f| %>
    <div class="col-lg-12 pad0">
        <div class="panel panel-default">
            <div class="panel-heading text-uppercase"><strong>Edit User-Information</strong></div>            
            <div class="panel-body">
              <%= render partial: 'form', locals: {f: f, action: 'edit'} %>
            </div>
        </div>
    </div>    
  <% end %>
</div>
<% end %>

app/views/users/index.html.erb
<% content_for :include_styles do %>
  <%= stylesheet_link_tag "dataTables.bootstrap.css" %>
  <%= stylesheet_link_tag "dataTables.responsive.min.css" %>  
<% end %>

<% content_for :include_scripts do %>
  <%= javascript_include_tag "jquery.dataTables.min.js" %>
  <%= javascript_include_tag "dataTables.bootstrap.min.js" %>
  <%= javascript_include_tag "dataTables.responsive.min.js" %>
  <%= javascript_include_tag "modal_confirmation_function.js" %>
<% end %>

<% content_for :page_icon do %>
  <i class="fa fa-group custom_icon" aria-hidden="true"></i>
<% end %>

<% content_for :body do %>
<div class="row">
  <div class="col-lg-12 pad0">
    <div class="tab-content" id="tab_holder">
      <ul class="nav nav-tabs custom_nav_tab">
        <li class="active"><a href="#partners" data-toggle="tab" class="tab190" id="partner_accounts">Partners Account <i class="fa fa-chain fa-fw user_tab_icon"></i></a></li>
        <li><a href="#clients" data-toggle="tab" class="tab190" id="client_accounts">Clients Account <i class="fa fa-briefcase fa-fw user_tab_icon"></i></a></li>
        <li><a href="#admins" data-toggle="tab" class="tab190" id="admin_accounts">Admin Account <i class="fa fa-gears fa-fw user_tab_icon"></i></a></li>
      </ul>
      
      <div class="tab-pane active" id="partners"><%= render partial: 'users/listing', locals: {users: @users, account: 'partners'}  %></div>
      <div class="tab-pane" id="clients"><%= render partial: 'users/listing', locals: {users: @users, account: 'clients'}  %></div>
      <div class="tab-pane" id="admins"><%= render partial: 'users/listing', locals: {users: @users, account: 'admins'}  %></div>
    </div>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<% content_for :include_styles do %>
  <%= stylesheet_link_tag "fileinput.min.css", media: "all" %>  
<% end %>

<% content_for :include_scripts do %>
  <%= javascript_include_tag "fileinput.min.js" %>
  <%= javascript_include_tag "clipboard.min.js"  %>
  <%= javascript_include_tag "users/generate_password.js" %>  
<% end %>

<% content_for :page_icon do %>
  <i class="fa fa-user custom_icon" aria-hidden="true"></i>
<% end %>

<% content_for :body do %>
<div class="row">
  <% if @user.errors.any? %>
    <div class="alert alert-danger custom_alert_notification">
      <button id="error_alert_x" type="button" class="close"><span aria-hidden="true">&times;</span></button>
      <strong>There was <%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</strong>
      <div id="errorExplanation">      
          <% @user.errors.full_messages.each do |msg| %>
          <p style="display: inline;">* <%= msg %></p><br />
          <% end %>
      </div>
    </div> 
  <% end %>
  <%= render partial: 'users/generate_password_modal' %>
  <%= form_for @user, :url => @users_path, :html => {:class => "form-horizontal", :multipart => true, :method => "post"} do |f| %>    
    <div class="col-lg-12 pad0">
        <div class="panel panel-default">
            <div class="panel-heading text-uppercase"><strong>New User-Information</strong></div>            
            <div class="panel-body">
              <%= render partial: 'form', locals: {f: f, action: 'new'} %>
            </div>
        </div>
    </div>    
  <% end %>
</div>
<% end %>