config/routes.rb
Rails.application.routes.draw do      
  scope '(:locale)', locale: /en|ja/ do
    resources :users, :applicants, :religions, :countries, :job_types, :projects, :job_orders, :file_types, :academic_abilities, :aptitude_tests, :pww_logos
    
    # AJAX REQUESTS
    ## Religions
    get 'get_all_religions' => 'religions#get_all_religions'
    get 'add_new_religion' => 'religions#add_new_religion'
    post 'edit_religion' => 'religions#edit_religion'
    get 'delete_religion' => 'religions#delete_religion'

    ## Job Types
    get 'get_all_job_types' => 'job_types#get_all_job_types'
    get 'add_new_job_type' => 'job_types#add_new_job_type'
    post 'edit_job_type' => 'job_types#edit_job_type'
    get 'delete_job_type' => 'job_types#delete_job_type'

    ## Countries
    get 'get_all_countries' => 'countries#get_all_countries'
    get 'add_new_country' => 'countries#add_new_country'
    post 'edit_country' => 'countries#edit_country'
    get 'delete_country' => 'countries#delete_country'

    ## Projects
    get 'get_all_projects' => 'projects#get_all_projects'
    get 'add_new_project' => 'projects#add_new_project'
    get 'delete_project' => 'projects#delete_project'
    get 'project_remove_document' => 'projects#project_remove_document'
    get 'view_project_applicants' => 'projects#view_project_applicants'
    post 'send_email_job_order' => 'projects#send_email_job_order'
    get 'project_chart' => 'home#project_chart'
    get 'get_last_sent_mail_date' => 'projects#get_last_sent_mail_date'

    ## Users
    get 'delete_user_account' => 'users#destroy'
    get 'delete_applicant' => 'applicants#destroy'

    ## File Type
    get 'get_all_file_types' => 'file_types#get_all_file_types'
    get 'add_new_file_type' => 'file_types#add_new_file_type'
    post 'edit_file_type' => 'file_types#edit_file_type'
    get 'delete_file_type' => 'file_types#delete_file_type'

    ## Academic Abilities
    get 'get_all_academic_abilities' => 'academic_abilities#get_all_academic_abilities'
    get 'add_new_academic_ability' => 'academic_abilities#add_new_academic_ability'
    post 'edit_academic_ability' => 'academic_abilities#edit_academic_ability'
    get 'delete_academic_ability' => 'academic_abilities#delete_academic_ability'

    ## Aptitude Tests
    get 'get_all_aptitude_tests' => 'aptitude_tests#get_all_aptitude_tests'
    get 'add_new_aptitude_test' => 'aptitude_tests#add_new_aptitude_test'
    post 'edit_aptitude_test' => 'aptitude_tests#edit_aptitude_test'
    get 'delete_aptitude_test' => 'aptitude_tests#delete_aptitude_test'

    ## Applicant Files
    get 'applicant_files' => 'applicant_files#index'
    get 'delete_applicant_file' => 'applicant_files#destroy'

    ## Search
    get 'search' => 'search#index'
    get 'quick_search' => 'search#quick_search', as: 'quick_search'
    post 'search_applicants' => 'search#search_applicants', as: 'search_applicants'    

    ## Applicants
    get 'lock_function' => 'applicants#lock_function'
    get 'video_interview' => 'applicants#video_interview'
    get 'video_self_introduction' => 'applicants#video_self_introduction'    
    get 'project_history' => 'applicants#project_history'
    get 'requests_for_applicant_record_deletion' => 'applicants#to_be_deleted'
    get 'request_for_delete_applicant' => 'applicants#request_for_delete_applicant'
    get 'restore_applicant' => 'applicants#restore_applicant'
    get 'make_comments_to_applicant' => 'applicants#make_comments_to_applicant'

    # PWW Logo
    get 'delete_pww_logo' => 'pww_logos#destroy'

    ## Generate PDF Reports
    get 'generate_applicant_report' => 'applicants#generate_applicant_report', as: 'generate_applicant_report'
    match 'generate_pdf_full_report' => 'search#generate_pdf_full_report', via: :get
    match 'generate_csv_full_report' => 'search#generate_csv_full_report', as: 'generate_csv_full_report', via: :get

    ## Authenticate Admin Password Before Record Deletion
    post 'authenticate_user_password' => 'users#authenticate_user_password'

    ## User Auth Functions    
    controller :login do
        get 'login' => :index, as: :login
        post 'authenticate_login' => :authenticate_login
        get 'logout' => :destroy
        # delete 'logout' => 'login#destroy'
    end
    
    mount Ckeditor::Engine => '/ckeditor'
    match 'home' => 'home#index', via: :get, as: 'home'
    root :to => 'login#index'
  end

  match '*path', :to => 'application#render_404', :via => :all, :locale => 'en' # render 404 page when routes not found
  match '/*locale/*path', to: redirect('/#{I18n.default_locale}/%{path}'), :via => :get # handles /bad-locale|anything/valid-path
  match '/*path', to: redirect('/#{I18n.default_locale}/%{path}'), :via => :get # handles /anything|valid-path-but-no-locale  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController  
  # authorize_resource :class => false#, parent: false

  layout 'cms'
  include CheckLoginModule
  include GetCommonDataModule
  include GetCommonFunctionModule

  before_action :check_login  

  # renders index page
  def index
    if session[:role] == 'client'
      redirect_to projects_path(locale: I18n.locale)
    end

    @page_title = "#{session[:role]} Dashboard"
    @menu = 'dashboard'    
    
    get_user_applicants
    get_user_projects
  
    if session[:role] == 'admin'
      @admins = User.admins
      @partners = User.partners
      @clients = User.clients        
    end
  end

  # returns current user' project details
  def project_chart    
    result = []
    get_user_projects.each do |project|
      result << {
        title: project.title,
        registered: project.count_associated_applicants(session[:role]),
        total: project.no_of_needed_applicants
      }
    end
    render json: result    
  end

  private
  # get current user's project, based on user role
  def get_user_projects
    if session[:role] == 'admin'
      @projects = Project.not_failed.order('created_at DESC').limit(6)
    elsif session[:role] == 'partner'
      @projects = current_user.partner_projects.not_failed.order('created_at DESC').limit(6)
    else #client
      @projects = current_user.client_projects.not_failed.order('created_at DESC').limit(6)
    end
  end

  # get current user's associated applicants, based on user role
  def get_user_applicants
    if session[:role] == 'admin'
      @applicants = filter_not_to_be_deleted(Applicant.all)
    elsif session[:role] == 'partner'
      @applicants = filter_not_to_be_deleted(current_user.partner_created_applicants.has_creator)
    else #client
      @applicants = filter_not_to_be_deleted(current_user.applicants.has_creator)
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_alert_notification.html.erb
<div id="success_alert" class="alert" style="display: <%= flash[:status] == 'success' ? 'block' : 'none' %>; <%= css %>">
  <button id="success_alert_x" type="button" class="close"><span aria-hidden="true">&times;</span></button>
  <strong>Well done! </strong>
  <p style="display: inline;" id="success_alert_message"><%= flash[:notice] %></p>
</div>

<div id="error_alert" class="alert alert-<%= flash[:status] %>" style="display: <%= flash[:status] == 'error' ? 'block' : 'none' %>; <%= css %>">
  <button id="error_alert_x" type="button" class="close"><span aria-hidden="true">&times;</span></button>
  <strong>Oh! </strong>
  <p style="display: inline;" id="error_alert_message"><%= flash[:notice] %></p>
</div>

app/views/home/_area_chart.html.erb
<div class="panel-heading">
<i class="fa fa-bar-chart-o fa-fw"></i> Area Chart Example
<div class="pull-right">
    <div class="btn-group">
        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
            Actions
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" role="menu">
            <li><a href="#">Action</a>
            </li>
            <li><a href="#">Another action</a>
            </li>
            <li><a href="#">Something else here</a>
            </li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a>
            </li>
        </ul>
    </div>
</div>
</div>

<div class="panel-body">
<div id="morris-area-chart"></div>
</div>

app/views/home/_bar_chart.html.erb
<div class="panel-heading">
    <div class="row">
        <div class="col-lg-5">
            <i class="fa fa-list-alt fa-fw"></i> Latest Projects List
        </div>
        <div class="col-lg-7">
            <i class="fa fa-bar-chart-o fa-fw"></i> Project's Progress Status
        </div>
    </div>
</div>                  
                        
<div class="panel-body">
    <div class="row">
        <div class="col-lg-5 pad-right0">
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped" style="font-size: 13px;">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Job Description</th>
                            <% if session[:role] == 'admin' %>
                                <th>Company</th>
                                <th>Partner & Client</th>
                            <% else %>                        
                                <th>Needed Applicants</th>
                                <th>Registered Applicants</th>
                            <% end %>
                        </tr>
                    </thead>
                    <tbody>
                        <% if @projects.empty? && session[:role] != 'admin' %>
                            <tr><td colspan="4">-No Project-</td></tr>
                        <% end %>

                        <% @projects.each do |project| %>
                        <% @count_associated = project.count_associated_applicants(session[:role])  %>
                        <tr>
                            <% if session[:role] == 'admin' %>
                                <td class="capitalize"><a href="/<%=I18n.locale%>/view_project_applicants?id=<%=project.id%>"><%= project.title %></a></td>
                                <td><%= project.job_type.try(:en_name) %></td>
                                <td><%= project.company_name %></td>                  
                                <td>* <%= project.partner.try(:fullname) %><br>* <%= project.client.try(:fullname) %></td>                                
                            <% else %>
                                <td class="capitalize"><%= project.title %></td>                            
                                <td><%= project.job_type.try(:en_name) %></td>                                
                                <td><%= project.no_of_needed_applicants %></td>
                                <td><%= @count_associated %></td>
                            </td>
                            <% end %>
                            
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div class="col-lg-7 pad-right0">
            <div id="morris-bar-chart"></div>
        </div>
    </div>
</div>

app/views/home/_categories.html.erb
<div class="row">
    <div class="col-lg-3 pad0 category_border_right3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-users fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= number_to_human(@applicants.count) %></div>
                        <div>Resumes</div>
                    </div>
                </div>
            </div>        
        </div>
    </div>

    <div class="col-lg-3 pad0 category_border_right2">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-plane fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= number_to_human(@applicants.in_progress.count) %></div>
                        <div>In-progress Resumes</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-3 pad0 category_border_right3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-tasks fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= number_to_human(@projects.count) %></div>
                        <div>Projects</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-3 pad0 category_border_left">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-support fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= number_to_human(@projects.in_progress.count) %></div>
                        <div>In-progress Projects</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/_chat.html.erb
<div class="panel-heading">
    <i class="fa fa-comments fa-fw"></i>
    Chat
    <div class="btn-group pull-right">
        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-chevron-down"></i>
        </button>
        <ul class="dropdown-menu slidedown">
            <li>
                <a href="#">
                    <i class="fa fa-refresh fa-fw"></i> Refresh
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-check-circle fa-fw"></i> Available
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-times fa-fw"></i> Busy
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-clock-o fa-fw"></i> Away
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <i class="fa fa-sign-out fa-fw"></i> Sign Out
                </a>
            </li>
        </ul>
    </div>
</div>
<!-- /.panel-heading -->
<div class="panel-body">
    <ul class="chat">
        <li class="left clearfix">
            <span class="chat-img pull-left">
                <img src="http://placehold.it/50/55C1E7/fff" alt="User Avatar" class="img-circle" />
            </span>
            <div class="chat-body clearfix">
                <div class="header">
                    <strong class="primary-font">Jack Sparrow</strong>
                    <small class="pull-right text-muted">
                        <i class="fa fa-clock-o fa-fw"></i> 12 mins ago
                    </small>
                </div>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.
                </p>
            </div>
        </li>
        <li class="right clearfix">
            <span class="chat-img pull-right">
                <img src="http://placehold.it/50/FA6F57/fff" alt="User Avatar" class="img-circle" />
            </span>
            <div class="chat-body clearfix">
                <div class="header">
                    <small class=" text-muted">
                        <i class="fa fa-clock-o fa-fw"></i> 13 mins ago</small>
                    <strong class="pull-right primary-font">Bhaumik Patel</strong>
                </div>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.
                </p>
            </div>
        </li>
        <li class="left clearfix">
            <span class="chat-img pull-left">
                <img src="http://placehold.it/50/55C1E7/fff" alt="User Avatar" class="img-circle" />
            </span>
            <div class="chat-body clearfix">
                <div class="header">
                    <strong class="primary-font">Jack Sparrow</strong>
                    <small class="pull-right text-muted">
                        <i class="fa fa-clock-o fa-fw"></i> 14 mins ago</small>
                </div>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.
                </p>
            </div>
        </li>
        <li class="right clearfix">
            <span class="chat-img pull-right">
                <img src="http://placehold.it/50/FA6F57/fff" alt="User Avatar" class="img-circle" />
            </span>
            <div class="chat-body clearfix">
                <div class="header">
                    <small class=" text-muted">
                        <i class="fa fa-clock-o fa-fw"></i> 15 mins ago</small>
                    <strong class="pull-right primary-font">Bhaumik Patel</strong>
                </div>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare dolor, quis ullamcorper ligula sodales.
                </p>
            </div>
        </li>
    </ul>
</div>
<!-- /.panel-body -->
<div class="panel-footer">
    <div class="input-group">
        <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here..." />
        <span class="input-group-btn">
            <button class="btn btn-warning btn-sm" id="btn-chat">
                Send
            </button>
        </span>
    </div>
</div>

app/views/home/_donut_chart.html.erb
<div class="panel-heading">
    <i class="fa fa-bar-chart-o fa-fw"></i> Donut Chart Example
</div>
<div class="panel-body">
    <div id="morris-donut-chart"></div>
    <a href="#" class="btn btn-default btn-block">View Details</a>
</div>

app/views/home/_navigator.html.erb
 <nav class="navbar navbar-default navbar-static-top nav_bg" role="navigation" style="margin-bottom: 0">    
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/<%= I18n.locale %>"><%= image_tag("/assets/pww_japan_header_small.png", class: 'nav_logo') %></a>
    </div>
    
    <%= render partial: 'home/upper_links' %>

    <% if session[:role] == 'admin'  %>
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search" style="padding: 15px 5px 15px 5px;">
                        <%= render partial: 'home/quick_search' %>
                    </li>
                    
                    <li id="dashboard"><a href="<%= home_path(locale: I18n.locale) %>"><i class="fa fa-desktop fa-fw"></i> Dashboard</a></li>
                    
                    <li id="<%= controller_name == 'search' ? @menu : '' %>"><a href="<%= search_path(:locale => I18n.locale) %>"><i class="fa fa-search fa-fw"></i> Advanced Search</a></li>

                    <li id="applicants">
                        <a href="#"><i class="fa fa-users fa-fw"></i> <span class="fa arrow"></span>Applicants</a>                    
                        <ul class="nav nav-second-level">
                            <li><a id="applicants_index" href="<%= applicants_path(:locale => I18n.locale) %>">List of Applicants</a></li>
                            <% if can? :create, Applicant %>
                                <li><a id="applicants_new" href="<%= new_applicant_path(:locale => I18n.locale) %>">New Applicant</a></li>
                            <% end %>

                            <% if can? :destroy, Applicant %>
                                <li><a id="requests_for_applicant_record_deletion" href="<%= requests_for_applicant_record_deletion_path(:locale => I18n.locale) %>">Requested To Be Deleted</a></li>
                            <% end %>
                        </ul>
                    </li>
                    
                    <li id="projects">
                        <a href="#"><i class="fa fa-gears fa-fw"></i> Project Management<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="<%= projects_path(:locale => I18n.locale) %>">List of Projects</a></li>
                            <li><a href="<%= new_project_path(:locale => I18n.locale) %>">Create Project</a></li>
                        </ul>
                    </li>
                    
                    <li id="users">
                        <a href="#"><i class="fa fa-key fa-fw"></i> <span class="fa arrow"></span> User Access</a>
                        <ul class="nav nav-second-level">
                            <li><a class="users_index" href="<%= users_path(:locale => I18n.locale) %>">User List</a></li>
                            <li><a class="users_new" href="<%= new_user_path(:locale => I18n.locale) %>">New User</a></li>
                        </ul>
                    </li>

                    <li id="pww_logos">
                        <a href="#"><i class="fa fa-bookmark-o fa-fw"></i> PDF Header Management<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a class="pww_logos_index" href="<%= pww_logos_path(:locale => I18n.locale) %>">Header List</a></li>
                            <li><a class="pww_logos_new" href="<%= new_pww_logo_path(:locale => I18n.locale) %>">New Header</a></li>
                        </ul>
                    </li>

                    <li id="data_management">
                        <a href="#"><i class="fa fa-database fa-fw"></i> <span class="fa arrow"></span> Data Management</a>
                        <ul class="nav nav-second-level">
                            <li><a class="academic_abilities_index" href="<%= academic_abilities_path(:locale => I18n.locale) %>">Academic Ability</a></li>
                            <li><a class="aptitude_tests_index" href="<%= aptitude_tests_path(:locale => I18n.locale) %>">Skill Check Tests</a></li>
                            <li><a class="countries_index" href="<%= countries_path(:locale => I18n.locale) %>">Countries</a></li>
                            <li><a class="file_types_index" href="<%= file_types_path(:locale => I18n.locale) %>">File Types</a></li>
                            <li><a class="job_types_index" href="<%= job_types_path(:locale => I18n.locale) %>">Job Types</a></li>
                            <li><a class="religions_index" href="<%= religions_path(:locale => I18n.locale) %>">Religions</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="bottom_pww">
                    <p>People World Wide | Admin v1.0</p>
                    <p>&copy; All rights reserved 2016</p>
                </div>
            </div>
            <!-- /.sidebar-collapse -->        
        </div>
    <% end %>
    <!-- /.navbar-static-side -->    
</nav>

app/views/home/_partners_navigator.html.erb
<div class="row non_admin_nav" style="width: 100%; margin-right: 0px; margin-left: 0px;">
    <div class="col-lg-8">
        <ul class="non_admin_ul">
            <li id="home_index"><a href="/<%= I18n.locale %>"><i class="fa fa-home"></i> Dashboard</a></li>
            <li id="applicants_index"><a href="<%= applicants_path(:locale => I18n.locale) %>"><i class="fa fa-users"></i> List of Applicants</a></li>
            <li id="projects_index"><a href="<%= projects_path(:locale => I18n.locale) %>"><i class="fa fa-list-alt"></i> My Projects</a></li>
            <li id="applicants_new"><a href="<%= new_applicant_path(:locale => I18n.locale) %>"><i class="fa fa-user"></i> Register Applicant</a></li>
            <li id="search_index"><a href="<%= search_path(:locale => I18n.locale) %>"><i class="fa fa-search"></i> Advanced Search</a></li>
        </ul>
    </div>
    <div class="col-lg-4 pad-left0">
        <div style="padding-top:5px;"></div>
        <!-- Quick Search For Partner's Account -->
        <%= render partial: 'home/quick_search' %>
    </div>
</div>

app/views/home/_quick_search.html.erb
<%= form_tag(quick_search_path(locale: I18n.locale), method: :get) do %>
  <div class="input-group custom-search-form">
      <input type="text" class="form-control" name="applicant_name" placeholder="Quick Search By Name..." required>
      <span class="input-group-btn">
          <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
      </span>
  </div>
<% end %>

app/views/home/_upper_links.html.erb
 <ul class="nav navbar-top-links navbar-right">
    <li class="hi_user">Hello, <span class="nav_gold"><%= session[:username] %></span>|</li>
    <li><div class="todayDate"><%= Time.new.strftime("%A, %d %B %Y") %></div></li>
    <% if can? :manage, Project %>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" title="Latest Project's Progress">
                <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-tasks">
                <% @latest_projects.each_with_index do |project, index| %>
                    <% @percent = percent_of(project.no_of_needed_applicants, project.count_associated_applicants(session[:role])) %>
                    <li>
                        <a href="/<%= I18n.locale %>/view_project_applicants?id=<%= project.id %>">
                            <div>
                                <p>
                                    <strong><%= project.title %></strong>
                                    <span class="pull-right text-muted"><%= @percent %>%</span>
                                </p>
                                <div class="progress progress-striped active" style="background-color: rgba(91,192,222,0.25);">
                                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= @percent %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @percent %>%">
                                        <span class="sr-only"><%= @percent %>%</span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                <% end %>           
                <li>
                    <a class="text-center" href="<%= projects_path(locale: I18n.locale) %>">
                        <strong>See All Projects</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
        </li>

        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" title="Requests to be deleted.">
                <span class="request_of_deletion_count"><%= @request_of_deletion.count %></span> <i class="glyphicon glyphicon-trash fa-fw"></i>
                <% if @request_of_deletion.count != 0 %><i class="fa fa-caret-down"></i><% end %>
            </a>
            <% if @request_of_deletion.count != 0 %>
                <ul class="dropdown-menu dropdown-messages view_all_deletion_request">
                    <% @request_of_deletion.limit(5).each do |request| %>
                        <li class="request_of_deletion_<%= request.id %>">
                            <div class="requests">
                                <span class="chat-img pull-left"><%= image_tag(user_profile_image(request.partner, 'thumb'), class: 'img-circle request_img height60') %></span>
                                <span class="space_normal"><strong class="text-capitalize maroon_text"><%= request.partner.try(:fullname) %></strong></span>
                                <span class="pull-right text-muted">
                                    <em class="request_delete_date"><%= time_ago_in_words(request.created_at) %> ago</em>
                                </span>
                            </div>
                            <div class="request_content">
                                <p><span class="chat-img pull-left"><%= image_tag(request.applicant.profile(:thumb), class: 'img-circle request_img height50') %></span></p>
                                <p class="text-capitalize"><b>Who:</b> <span class="deletion_gold"><%= request.applicant.try(:name).try(:capitalize) %></span></p>
                                <p><b>Why:</b> <%= request.reason %></p>
                            </div>
                        </li>
                        <li class="divider request_of_deletion_<%= request.id %>"></li>
                    <% end %>
                    
                    <li>
                        <a class="text-center active_menu" href="<%= requests_for_applicant_record_deletion_path(:locale => I18n.locale) %>">
                            <strong>View Requests</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
            <% end %>
        </li>
    <% end %>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= image_tag(session[:profile], class: 'profile_small') %>&nbsp;
        <i class="fa fa-fw"></i><i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <% if can? :update, User %>
                <li><a href="<%= edit_user_path(session[:user_id], locale: I18n.locale) %>"><i class="fa fa-gears fa-fw"></i> User Profile</a></li>
                <li class="divider"></li>
            <% end %>            
            <li>
                <!-- <#%= link_to 'Logout', logout_path(locale: I18n.locale), method: :delete %> -->
                <a class="logout" rel="nofollow" data-method="delete" href="/<%= I18n.locale %>/logout"><i class="fa fa-sign-out fa-fw"></i> ログアウト/Logout</a>
            </li>
        </ul>
    </li>    
</ul>