config/routes.rb
Rails.application.routes.draw do      
  scope '(:locale)', locale: /en|ja/ do
    resources :users, :applicants, :religions, :countries, :job_types, :projects, :job_orders, :file_types, :academic_abilities, :aptitude_tests, :pww_logos
    
    # AJAX REQUESTS
    ## Religions
    get 'get_all_religions' => 'religions#get_all_religions'
    get 'add_new_religion' => 'religions#add_new_religion'
    post 'edit_religion' => 'religions#edit_religion'
    get 'delete_religion' => 'religions#delete_religion'

    ## Job Types
    get 'get_all_job_types' => 'job_types#get_all_job_types'
    get 'add_new_job_type' => 'job_types#add_new_job_type'
    post 'edit_job_type' => 'job_types#edit_job_type'
    get 'delete_job_type' => 'job_types#delete_job_type'

    ## Countries
    get 'get_all_countries' => 'countries#get_all_countries'
    get 'add_new_country' => 'countries#add_new_country'
    post 'edit_country' => 'countries#edit_country'
    get 'delete_country' => 'countries#delete_country'

    ## Projects
    get 'get_all_projects' => 'projects#get_all_projects'
    get 'add_new_project' => 'projects#add_new_project'
    get 'delete_project' => 'projects#delete_project'
    get 'project_remove_document' => 'projects#project_remove_document'
    get 'view_project_applicants' => 'projects#view_project_applicants'
    post 'send_email_job_order' => 'projects#send_email_job_order'
    get 'project_chart' => 'home#project_chart'
    get 'get_last_sent_mail_date' => 'projects#get_last_sent_mail_date'

    ## Users
    get 'delete_user_account' => 'users#destroy'
    get 'delete_applicant' => 'applicants#destroy'

    ## File Type
    get 'get_all_file_types' => 'file_types#get_all_file_types'
    get 'add_new_file_type' => 'file_types#add_new_file_type'
    post 'edit_file_type' => 'file_types#edit_file_type'
    get 'delete_file_type' => 'file_types#delete_file_type'

    ## Academic Abilities
    get 'get_all_academic_abilities' => 'academic_abilities#get_all_academic_abilities'
    get 'add_new_academic_ability' => 'academic_abilities#add_new_academic_ability'
    post 'edit_academic_ability' => 'academic_abilities#edit_academic_ability'
    get 'delete_academic_ability' => 'academic_abilities#delete_academic_ability'

    ## Aptitude Tests
    get 'get_all_aptitude_tests' => 'aptitude_tests#get_all_aptitude_tests'
    get 'add_new_aptitude_test' => 'aptitude_tests#add_new_aptitude_test'
    post 'edit_aptitude_test' => 'aptitude_tests#edit_aptitude_test'
    get 'delete_aptitude_test' => 'aptitude_tests#delete_aptitude_test'

    ## Applicant Files
    get 'applicant_files' => 'applicant_files#index'
    get 'delete_applicant_file' => 'applicant_files#destroy'

    ## Search
    get 'search' => 'search#index'
    get 'quick_search' => 'search#quick_search', as: 'quick_search'
    post 'search_applicants' => 'search#search_applicants', as: 'search_applicants'    

    ## Applicants
    get 'lock_function' => 'applicants#lock_function'
    get 'video_interview' => 'applicants#video_interview'
    get 'video_self_introduction' => 'applicants#video_self_introduction'    
    get 'project_history' => 'applicants#project_history'
    get 'requests_for_applicant_record_deletion' => 'applicants#to_be_deleted'
    get 'request_for_delete_applicant' => 'applicants#request_for_delete_applicant'
    get 'restore_applicant' => 'applicants#restore_applicant'
    get 'make_comments_to_applicant' => 'applicants#make_comments_to_applicant'

    # PWW Logo
    get 'delete_pww_logo' => 'pww_logos#destroy'

    ## Generate PDF Reports
    get 'generate_applicant_report' => 'applicants#generate_applicant_report', as: 'generate_applicant_report'
    match 'generate_pdf_full_report' => 'search#generate_pdf_full_report', via: :get
    match 'generate_csv_full_report' => 'search#generate_csv_full_report', as: 'generate_csv_full_report', via: :get

    ## Authenticate Admin Password Before Record Deletion
    post 'authenticate_user_password' => 'users#authenticate_user_password'

    ## User Auth Functions    
    controller :login do
        get 'login' => :index, as: :login
        post 'authenticate_login' => :authenticate_login
        get 'logout' => :destroy
        # delete 'logout' => 'login#destroy'
    end
    
    mount Ckeditor::Engine => '/ckeditor'
    match 'home' => 'home#index', via: :get, as: 'home'
    root :to => 'login#index'
  end

  match '*path', :to => 'application#render_404', :via => :all, :locale => 'en' # render 404 page when routes not found
  match '/*locale/*path', to: redirect('/#{I18n.default_locale}/%{path}'), :via => :get # handles /bad-locale|anything/valid-path
  match '/*path', to: redirect('/#{I18n.default_locale}/%{path}'), :via => :get # handles /anything|valid-path-but-no-locale  
end

app/models/pww_logo.rb
class PwwLogo < ActiveRecord::Base
  has_many :users
  scope :active, -> { where(status: true) }

  # validates presence of the following, cannot be blank
  validates_presence_of :title, :content, :logo

  # allows the system to uplaod file, under logo prefix
  has_attached_file :logo, :styles => {:medium => "300x150>"}, # is for cropping
    :url  => "/images/pww_logo/:id/:style/:basename.:extension",
    :path => ":rails_root/public/images/pww_logo/:id/:style/:basename.:extension",
    :default_url => '/assets/default_avatar.jpg',
    :default_style => :medium
  
  # validates attachment, should be an image only
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
  before_post_process :transliterate_file_name
  
  # validates file name for readable name
  def transliterate_file_name
    extension = File.extname(logo.original_filename).gsub(/^\.+/, '')
    filename = logo.original_filename.gsub(/\.#{extension}$/, '')
    self.logo.instance_write(:file_name, "#{transliterate(filename)}.#{transliterate(extension)}")
  end
  
  def transliterate(str)
    s = Iconv.iconv('ascii//ignore//translit', 'utf-8', str).to_s
    s.downcase!
    s.gsub!(/'/, '')
    s.gsub!(/[^A-Za-z0-9]+/, ' ')
    s.strip!
    s.gsub!(/\ +/, '-')
    return s
  end
end

app/controllers/pww_logos_controller.rb
class PwwLogosController < ApplicationController
  load_and_authorize_resource

  layout 'cms'
  include CheckLoginModule
  before_action :check_login

  # renders index page
  def index
    @page_title = 'PDF Header Management'
  end
 
  # renders new page
  def new
    @page_title = 'Add New PDF Header'
  end

  # renders edit page
  def edit
    @menu = 'pww_logos'
    @page_title = 'Edit PDF Header' 
  end

  # creates new PWW Logo, from posted form in new page
  def create
    @page_title = 'Add New PDF Header'
    if @pww_logo.save
      flash.keep[:status] = 'success'
      flash.keep[:notice] = 'New PDF Header was successfully created.'
      redirect_to pww_logos_path(:locale => I18n.locale)
    else
      flash.keep[:status] = 'error'
      flash.keep[:notice] = 'Sorry, there was an error saving.'
      @menu = 'pww_logos'
      render action: 'new'
    end
  end
  
  # updates PWW Logo, from posted form in edit page
  def update
    if @pww_logo.update_attributes(pww_logo_params)
      flash[:status] = 'success'
      flash[:notice] = "#{@pww_logo.title} information was successfully updated."
      redirect_to pww_logos_path(:locale => I18n.locale)
    else
      @menu = 'pww_logos'
      @page_title = 'Edit PDF Header'
      flash[:status] = 'error'
      flash[:notice] = 'Sorry, there was an error updating.'
      render action: 'edit'
    end
  end

  # deletes PWW Logo record, submitted by ajax
  def destroy
    unless @pww_logo.nil?
      @pww_logo.destroy
      render json: {status: 'success', message: 'You have successfully deleted PDF Header.'}
    else
      render json: {status: 'error', message: 'Sorry, unable to find record.'}
    end    
  end
        
  private
  def pww_logo_params
    params.require(:pww_logo).permit!
  end
end

app/helpers/pww_logos_helper.rb
module PwwLogosHelper
end

app/views/pww_logos/_form.html.erb
<div class="form-group">
  <div class="col-md-12">
    <label>Header Title:</label>
    <%= f.text_field :title, :class => "form-control", :placeholder => "Logo Title *", autofocus: true, required: '', autocomplete: 'off' %>
  </div>
</div>

<div class="form-group">
  <div class="col-md-12">
    <%= image_tag(@pww_logo.logo.url(:medium), :class => '') if action == 'edit' %>
    <br>
    <label>Upload Logo:</label>
    <input name="pww_logo[logo]" id="pww_logo_image" type="file" class="file" data-preview-file-type="text" data-show-preview="true" data-show-upload="false" data-show-caption="true" />
  </div>
</div>

<div class="form-group">
  <div class="col-md-12">
    <label>Company Address:</label>
    <%= f.cktext_area :content, ckeditor: { toolbar: 'mini' }%>
  </div>
</div>

<div class="col-md-12 pad0">
  <div class="text-right">
    <a href="<%= pww_logos_path(locale: I18n.locale) %>" class="btn btn-warning btn-lg long-btn">CANCEL</a>
    <%= f.submit 'SAVE NOW', class: 'btn btn-danger btn-lg long-btn' %>
  </div>
</div>

app/views/pww_logos/edit.html.erb
<% content_for :include_styles do %>
  <%= stylesheet_link_tag "fileinput.min.css", media: "all" %>  
<% end %>

<% content_for :include_scripts do %>
  <%= javascript_include_tag "fileinput.min.js" %>
<% end %>

<% content_for :page_icon do %>
  <i class="fa fa-user custom_icon" aria-hidden="true"></i>
<% end %>

<% content_for :body do %>
<div class="row">  
  <% if @pww_logo.errors.any? %>
    <div class="alert alert-danger custom_alert_notification">
      <button id="error_alert_x" type="button" class="close"><span aria-hidden="true">&times;</span></button>
      <strong>There was <%= pluralize(@pww_logo.errors.count, "error") %> prohibited this post from being saved:</strong>
      <div id="errorExplanation">      
          <% @pww_logo.errors.full_messages.each do |msg| %>
          <p style="display: inline;">* <%= msg %></p><br />
          <% end %>
      </div>
    </div> 
  <% end %>

  <%= form_for(@pww_logo, :url => pww_logo_path(@pww_logo, :locale => I18n.locale), :html => {:class => "form-horizontal", :multipart => true}) do |f| %>
    <div class="col-lg-12 pad0">
        <div class="panel panel-default">
          <div class="panel-heading text-uppercase"><strong>Edit Header Information</strong></div>            
          <div class="panel-body"><%= render partial: 'form', locals: {f: f, action: 'edit'} %></div>
        </div>
    </div>     
  <% end %>
</div>
<% end %>

app/views/pww_logos/index.html.erb
<% content_for :include_styles do %>
  <%= stylesheet_link_tag "dataTables.bootstrap.css" %>
  <%= stylesheet_link_tag "dataTables.responsive.min.css" %>  
<% end %>

<% content_for :include_scripts do %>
  <%= javascript_include_tag "jquery.dataTables.min.js" %>
  <%= javascript_include_tag "dataTables.bootstrap.min.js" %>
  <%= javascript_include_tag "dataTables.responsive.min.js" %>
  <%= javascript_include_tag "modal_confirmation_function.js" %>
<% end %>

<% content_for :page_icon do %>
  <i class="fa fa-bookmark-o custom_icon" aria-hidden="true"></i>
<% end %>

<% content_for :body do %>
<div class="row">
  <div class="col-lg-12 pad0">
      <div class="panel panel-default">
        <div class="panel-heading">
            <strong>List of Headers</strong>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <div class="dataTable_wrapper">
              <table class="table table-striped table-bordered table-hover" id="makeDataTable">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Logo</th>
                    <th>Address</th>
                    <th>Last Updated At</th>                    
                    <th class="text-center">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @pww_logos.each do |pww| %>
                    <tr>
                      <td><%= pww.title %></td>
                      <td><%= image_tag(pww.logo.url(:medium), :class => '') %></td>
                      <td><%= raw(pww.content) %></td>
                      <td><%= pww.updated_at.to_time.strftime("%a, %e %b %Y %H:%M") %></td>                      
                      <td class="text-center">
                        <a href="<%= edit_pww_logo_path(pww, :locale => I18n.locale) %>"><i class="fa fa-edit list_icon" aria-hidden="true"></i></a>                        
                        <a href="#" class='delete_pww_logo' data-id="<%= pww.id %>" title="Delete <%= pww.title %>"><i class="fa fa-remove list_icon" aria-hidden="true"></i></a>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>    
  </div>
</div>
<% end %>

app/views/pww_logos/new.html.erb
<% content_for :include_styles do %>
  <%= stylesheet_link_tag "fileinput.min.css", media: "all" %>  
<% end %>

<% content_for :include_scripts do %>
  <%= javascript_include_tag "fileinput.min.js" %>
  <%= javascript_include_tag "clipboard.min.js"  %>
  <%= javascript_include_tag "generate_password.js" %>
<% end %>

<% content_for :page_icon do %>
  <i class="fa fa-bookmark-o custom_icon" aria-hidden="true"></i>
<% end %>

<% content_for :body do %>
<div class="row">
  <% if @pww_logo.errors.any? %>
    <div class="alert alert-danger custom_alert_notification">
      <button id="error_alert_x" type="button" class="close"><span aria-hidden="true">&times;</span></button>
      <strong>There was <%= pluralize(@pww_logo.errors.count, "error") %> prohibited this post from being saved:</strong>
      <div id="errorExplanation">      
          <% @pww_logo.errors.full_messages.each do |msg| %>
          <p style="display: inline;">* <%= msg %></p><br />
          <% end %>
      </div>
    </div> 
  <% end %>
  
  <%= form_for @pww_logo, :url => @pww_logos_path, :html => {:class => "form-horizontal", :multipart => true, :method => "post"} do |f| %>    
    <div class="col-lg-12 pad0">
        <div class="panel panel-default">
            <div class="panel-heading text-uppercase"><strong>New Header Information</strong></div>
            <div class="panel-body"><%= render partial: 'form', locals: {f: f, action: 'new'} %></div>
        </div>
    </div>    
  <% end %>
</div>
<% end %>