config/routes.rb
Rails.application.routes.draw do      
  scope '(:locale)', locale: /en|ja/ do
    resources :users, :applicants, :religions, :countries, :job_types, :projects, :job_orders, :file_types, :academic_abilities, :aptitude_tests, :pww_logos
    
    # AJAX REQUESTS
    ## Religions
    get 'get_all_religions' => 'religions#get_all_religions'
    get 'add_new_religion' => 'religions#add_new_religion'
    post 'edit_religion' => 'religions#edit_religion'
    get 'delete_religion' => 'religions#delete_religion'

    ## Job Types
    get 'get_all_job_types' => 'job_types#get_all_job_types'
    get 'add_new_job_type' => 'job_types#add_new_job_type'
    post 'edit_job_type' => 'job_types#edit_job_type'
    get 'delete_job_type' => 'job_types#delete_job_type'

    ## Countries
    get 'get_all_countries' => 'countries#get_all_countries'
    get 'add_new_country' => 'countries#add_new_country'
    post 'edit_country' => 'countries#edit_country'
    get 'delete_country' => 'countries#delete_country'

    ## Projects
    get 'get_all_projects' => 'projects#get_all_projects'
    get 'add_new_project' => 'projects#add_new_project'
    get 'delete_project' => 'projects#delete_project'
    get 'project_remove_document' => 'projects#project_remove_document'
    get 'view_project_applicants' => 'projects#view_project_applicants'
    post 'send_email_job_order' => 'projects#send_email_job_order'
    get 'project_chart' => 'home#project_chart'
    get 'get_last_sent_mail_date' => 'projects#get_last_sent_mail_date'

    ## Users
    get 'delete_user_account' => 'users#destroy'
    get 'delete_applicant' => 'applicants#destroy'

    ## File Type
    get 'get_all_file_types' => 'file_types#get_all_file_types'
    get 'add_new_file_type' => 'file_types#add_new_file_type'
    post 'edit_file_type' => 'file_types#edit_file_type'
    get 'delete_file_type' => 'file_types#delete_file_type'

    ## Academic Abilities
    get 'get_all_academic_abilities' => 'academic_abilities#get_all_academic_abilities'
    get 'add_new_academic_ability' => 'academic_abilities#add_new_academic_ability'
    post 'edit_academic_ability' => 'academic_abilities#edit_academic_ability'
    get 'delete_academic_ability' => 'academic_abilities#delete_academic_ability'

    ## Aptitude Tests
    get 'get_all_aptitude_tests' => 'aptitude_tests#get_all_aptitude_tests'
    get 'add_new_aptitude_test' => 'aptitude_tests#add_new_aptitude_test'
    post 'edit_aptitude_test' => 'aptitude_tests#edit_aptitude_test'
    get 'delete_aptitude_test' => 'aptitude_tests#delete_aptitude_test'

    ## Applicant Files
    get 'applicant_files' => 'applicant_files#index'
    get 'delete_applicant_file' => 'applicant_files#destroy'

    ## Search
    get 'search' => 'search#index'
    get 'quick_search' => 'search#quick_search', as: 'quick_search'
    post 'search_applicants' => 'search#search_applicants', as: 'search_applicants'    

    ## Applicants
    get 'lock_function' => 'applicants#lock_function'
    get 'video_interview' => 'applicants#video_interview'
    get 'video_self_introduction' => 'applicants#video_self_introduction'    
    get 'project_history' => 'applicants#project_history'
    get 'requests_for_applicant_record_deletion' => 'applicants#to_be_deleted'
    get 'request_for_delete_applicant' => 'applicants#request_for_delete_applicant'
    get 'restore_applicant' => 'applicants#restore_applicant'
    get 'make_comments_to_applicant' => 'applicants#make_comments_to_applicant'

    # PWW Logo
    get 'delete_pww_logo' => 'pww_logos#destroy'

    ## Generate PDF Reports
    get 'generate_applicant_report' => 'applicants#generate_applicant_report', as: 'generate_applicant_report'
    match 'generate_pdf_full_report' => 'search#generate_pdf_full_report', via: :get
    match 'generate_csv_full_report' => 'search#generate_csv_full_report', as: 'generate_csv_full_report', via: :get

    ## Authenticate Admin Password Before Record Deletion
    post 'authenticate_user_password' => 'users#authenticate_user_password'

    ## User Auth Functions    
    controller :login do
        get 'login' => :index, as: :login
        post 'authenticate_login' => :authenticate_login
        get 'logout' => :destroy
        # delete 'logout' => 'login#destroy'
    end
    
    mount Ckeditor::Engine => '/ckeditor'
    match 'home' => 'home#index', via: :get, as: 'home'
    root :to => 'login#index'
  end

  match '*path', :to => 'application#render_404', :via => :all, :locale => 'en' # render 404 page when routes not found
  match '/*locale/*path', to: redirect('/#{I18n.default_locale}/%{path}'), :via => :get # handles /bad-locale|anything/valid-path
  match '/*path', to: redirect('/#{I18n.default_locale}/%{path}'), :via => :get # handles /anything|valid-path-but-no-locale  
end

app/models/project.rb
class Project < ActiveRecord::Base
  include GetCommonDataModule
  has_many :applicants
  has_many :applicant_project_history, dependent: :destroy
  belongs_to :partner, :class_name => 'User', :foreign_key => :partner_id
  belongs_to :client, :class_name => 'User', :foreign_key => :client_id
  # belongs_to :user

  belongs_to :country
  belongs_to :job_type

  scope :by_client, -> (client_id) {where(client_id: client_id)}
  scope :by_partner, -> (partner_id) {where(partner_id: partner_id)}
  scope :by_partner_or_client, -> (user_id) { where('client_id = ? OR partner_id = ?', user_id, user_id) }
  scope :not_failed, -> { where.not(status: 'Failed') }
  scope :in_progress, -> { where(status: 'In-progress') }
  scope :waiting, -> { where(status: 'Waiting') }
  scope :failed, -> { where(status: 'Failed') }
  scope :done, -> { where(status: 'Done') }

  # allows the system to uplaod file, under document prefix
  has_attached_file :document,
  :url  => "/documents/projects/:id/:basename.:extension",
  :path => ":rails_root/public/documents/projects/:id/:basename.:extension"

  # validates presence of the following fields
  validates_presence_of :title, :description, :partner_id, :client_id, :country_id, :job_type_id, :status, :no_of_needed_applicants

  # validates file type before uplaoding
  validates_attachment :document, 
    :content_type => {
    :content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)
  }

  # this is for selection purposes, combines Project's title and job type
  def select_project_with_description
    "#{title}  |  #{self.job_type.try(:en_name)}"
    # or direct method in view lambda { |r| "#{r.title} | #{r.description}" }
  end

  # counts Project's associated applicants
  def count_associated_applicants(role)
    if role == 'client'
      self.applicants.not_waiting.has_creator.not_to_be_deleted(get_all_requested_to_be_deleted_applicant.pluck(:applicant_id)).count
    else
      self.applicants.not_to_be_deleted(get_all_requested_to_be_deleted_applicant.pluck(:applicant_id)).count
    end
  end

  # for Advanced Searching, either by client or partner
  def self.get_by_client_or_partner(client_id, partner_id)    
    clients = Project.by_client(client_id).group(:id).pluck(:id).flatten
    partners = Project.by_partner(partner_id).group(:id).pluck(:id).flatten
    
    project_ids = (clients<<partners).flatten.uniq
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource except: [:view_project_applicants]
  require 'date'
  layout 'cms'
  include CheckLoginModule
  include GetCommonDataModule
  include GetCommonFunctionModule
  include ApplicationHelper
  
  before_action :check_login, :set_data

  # returns Country & JobType records
  def set_data
    get_countries
    get_job_types
  end

  def index
    if session[:role] == 'client'
      @page_title = 'プロジェクトリスト / Projects List'
    else
      @page_title = '管理画面/Projects List & Management'
    end

    @projects = @projects.includes(:job_type, :country).order('created_at DESC')
  end

  def show
    @projects = @projects.order('created_at DESC')
    render :action => "index"
  end

  def edit
    @menu = 'projects'
    @page_title = "Edit Project"
  end

  def send_email_job_order
    begin
      @project = Project.find(params[:project_id])

      users = User.where(id: params[:receiver_ids])
      users.each do |u|
        if u.email
          ProjectMailer.send_job_order_mail(@project, u.email).deliver_now
        end
      end
      
      # ProjectJob.perform_later(@project, params[:receiver_ids]) # activate this when using SideKiq

      @project.last_email_sent = Time.new
      @project.save
      
      render json: {status: 'success', message: "#{@project.title} email Job Order was successfully sent!"}
    rescue => error
      render json: {status: 'error', message: error.message}
    end
  end

  def new
    @page_title = 'Create Project'
  end

  def create
    @page_title = 'Create Project'
    # @project = Project.create(project_params)
    @project.last_updated_by = session[:username]
    if @project.save
      flash.keep[:status] = 'success'
      flash.keep[:notice] = 'New Project was successfully created.'
      redirect_to projects_path(:locale => I18n.locale)
    else
      @page_title = 'Create Project'
      flash.keep[:status] = 'error'
      flash.keep[:notice] = 'Sorry, there was an error saving.'
      render :action => 'new'
    end
  end

  def update
    @project.last_updated_by = session[:username]
    if @project.update_attributes(project_params)   #project_params.reject{|k,v| v.blank?}            
      flash[:status] = 'success'
      flash[:notice] = "#{@project.title} was successfully updated."
      redirect_to projects_path(:locale => I18n.locale)
    else
      @page_title = 'Edit Project'
      flash[:status] = 'error'
      flash[:notice] = 'Sorry, there was an error updating.'
      render :action => 'edit'
    end
  end

  def project_remove_document
    begin
      @project.update_attribute(:document, nil)      

      render json: {status: 'success', message: 'Document was successfully removed.'}
    rescue => error
      render json: {status: 'error', message: "Sorry, #{error.message}"}
    end
  end


  def delete_project
    begin
      @project.destroy
      render json: {status: 'success', message: "Project #{@project.title} was successfully deleted."}
    rescue => error
      render json: {status: 'error', message: error.message}
    end
  end

  def view_project_applicants    
    @menu = 'projects'
    @project = Project.find(params[:id])

    # For default parameters in getting scores in listing
    # get_academic_abilities
    # get_aptitude_tests

    if (!['In-progress', 'Confirmed'].include? @project.try(:status)) && session[:role] == 'client'
      render_404
    end

    @page_title = "#{@project.company_name}"
    if session[:role] == 'client'
      @applicants = filter_not_to_be_deleted(@project.applicants.not_waiting).includes(:country, :religion)
    else
      @applicants = filter_not_to_be_deleted(@project.applicants).includes(:country, :religion) 
    end
    session[:previous_controller] = 'projects'
    session[:previous_project] = @project.id    
  end

  def get_last_sent_mail_date
    render json: {when: check_last_sent(@project.last_email_sent)}
  end

  private
  def project_params
    params.require(:project).permit(:title, :company_name, :partner_id, :client_id, :country_id, :job_type_id, :document, :no_of_needed_applicants, :status, :description, :notes)    
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_listing.html.erb
<div class="panel panel-default">
  <!-- <div class="panel-heading"><strong>プロジェクトの詳細 / Project's Details</strong></div> -->
  <div class="panel-body">
    <div class="table-responsive">
      <div class="dataTable_wrapper">
        <table class="table table-striped table-bordered table-hover makeDataTable" id="dataTable_<%= id %>">
          <thead>
            <tr>
              <th style="width: 13%">タイトル/Title</th>
              <th style="width: 13%">会社名/Company</th>
              <% if can? :manage, Project %><th style="width: 10%;">Partner & Client</th><% end %>
              <th style="width: 7%">国/Country</th>
              <th style="width: 10%">業種/Job Type</th>
              <% if session[:role] != 'client' %><th style="width: 5%;" class="text-center">添付ファイル/File</th><% end %>
              <th style="width: 12%">進行状況/Progress</th>
              <th style="width: 7%;">ステータス/Status</th>
              <% if can? :manage, Project %><th style="width: 8%">Updated By/At</th><% end %>
              <th style="width: 7%" class="text-center">アクション/Action</th>
            </tr>
          </thead>
          <tbody>
          <%
            case status
            when 'In-progress'
              projects = projects.in_progress
            when 'Waiting'
              projects = projects.waiting
            when 'Failed'
              projects = projects.failed
            when 'Done'
              projects = projects.done
            end
          %>
          <% projects.each do |project| %>
          <tr>
            <td><%= project.title %></td>
            <td><%= project.company_name %></td>
            <% if can? :manage, Project %><td>*<%= project.try(:partner).try(:fullname) %><br>*<%= project.try(:client).try(:fullname)  %></td><% end %>
            <td><%= raw(to_break(project.country.try(:combine_jp_and_en_name))) %></td>
            <td><%= raw(to_break(project.job_type.try(:combine_jp_and_en_name))) %></td>
            <% if session[:role] != 'client' %>
              <td class="text-center">
                <% unless project.document_file_name.nil? %>
                  <%= image_tag(icon_for(File.extname(project.document.url).try(:downcase)), style: 'height: 20px') %>
                <% else %>
                No-File
                <% end %>
              </td>
            <% end %>
            <td>
              <%
                @count_associated = project.count_associated_applicants(session[:role])
                @percent = percent_of(project.no_of_needed_applicants, @count_associated)
              %>
              <p><strong>レジュメ数:</strong> <b><%= @count_associated %><b>/</b><%= project.no_of_needed_applicants %></b></p>                    
              <div class="progress progress-striped active margin_bottom_0" style="background-color: rgba(91,192,222,0.25);">
                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= @percent %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @percent %>%">
                    <span class="sr-only"><%= @percent %>%</span>
                </div>
              </div>
              <%= project_percentage(@percent) %>
            </td>
            <td><%= raw(helper_progress_status(project.status)) %></td>                          
            <% if can? :manage, Project %>
              <td>
                <b><%= project.last_updated_by %></b>
                <br><%= project.updated_at.to_time.strftime("%e %b %Y %H:%M") %>
              </td>
            <% end %>
            <td class="text-center">
            <% if can? :read, Project %>
              <a href='/<%=I18n.locale%>/view_project_applicants?id=<%=project.id%>' title='View Applicants under <%= project.title %>'><i class='fa fa-users font20 view_info' aria-hidden='true'></i></a>&nbsp;
            <% end %>

            <% if can? :destroy, Project %>
              <a href='#' class='delete_project' data-id="<%= project.id %>" title='Remove <%= project.title %>'><i class='fa fa-remove font20 remove_added' aria-hidden='true'></i></a>&nbsp;
              <a href='<%= edit_project_path(project, locale: I18n.locale) %>' title='Edit <%= project.title %>'><i class='fa fa-edit font20' aria-hidden='true'></i></a>
              <% if Rails.env.development? %>
              &nbsp;
              <a href='#' class="send_mail" data-id="<%=project.id%>" data-partner="<%=project.partner.id%>|<%=project.partner.try(:fullname)%>" data-client="<%=project.client.id%>|<%=project.client.try(:fullname)%>" title='Send <%= project.title %> Email Job Order'>
                <i class='fa fa-envelope-o font20 mail'></i>
              </a>
              <% end %>
            <% end %>
            </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
</div>
</div>

app/views/projects/_projects_form.html.erb
<div class="form-group">
  <label>Project Title:</label>
  <%= f.text_field :title, :class => "form-control", :placeholder => "Project Title *", autofocus: true, required: '', autocomplete: 'off' %>
</div>

<div class="form-group">
  <label>Company Name:</label>
  <%= f.text_field :company_name, :class => "form-control", :placeholder => "Company Name *", autofocus: true, required: '', autocomplete: 'off' %>
</div>

<div class="form-group">
  <label>Description:</label>
  <%= f.cktext_area :description%>
  <!-- , ckeditor: { uiColor: '#AADC6E', toolbar: 'mini' } -->
</div>

<div class="col-lg-12 pad0">
  <div class="col-lg-6 pad-left0">
    <div class="form-group">
      <label>Partner Assigned:</label>
      <%= f.select(:partner_id, User.partners.collect {|p| [ p.fullname, p.id ] }, {include_blank: '-select here-', :selected => @project.partner_id}, { class: 'form-control', required: '' }) %>
    </div>
  </div>
  <div class="col-lg-6 pad-right0">
    <div class="form-group">
      <label>Client Assigned:</label>
      <%= f.select(:client_id, User.clients.collect {|p| [ p.fullname, p.id ] }, {include_blank: '-select here-', :selected => @project.client_id}, { class: 'form-control', required: '' }) %>
    </div>
  </div>


  <div class="col-lg-6 pad-left0">
    <div class="form-group">
      <label>No. of needed applicants:</label>            
      <%= f.text_field :no_of_needed_applicants, :class => "form-control", type: 'number', min: '0', :placeholder => "No. of applicants needed *", required: '', autocomplete: 'off' %>
    </div>
  </div>
  <div class="col-lg-6 pad-right0">
    <div class="form-group">
      <label>Country of work</label>
       <%= f.select(:country_id, @countries.collect {|c| [ "#{c.jp_name}/#{c.en_name}", c.id ] }, {include_blank: '-select here-', :selected => @project.country_id}, { class: 'form-control', required: '' }) %>
    </div>
  </div>

   <div class="col-lg-6 pad-left0">
    <div class="form-group">
      <label>Job Description</label>
      <%= f.select(:job_type_id, @job_types.collect {|j| [ "#{j.jp_name}/#{j.en_name}", j.id ] }, {include_blank: '-select here-', :selected => @project.job_type_id}, { class: 'form-control', required: '' }) %>
    </div>
  </div>
  <div class="col-lg-6 pad-right0">
    <div class="form-group">
      <label>Status:</label>
      <%= f.select :status, options_for_select([ "In-progress", "Waiting", "Failed", "Done" ], @project.status),{include_blank: '-select here-'}, {class: 'form-control', required: ''} %>
    </div>
  </div>
</div>

<div class="form-group">  
  <label class="valid_files show_main_document" style="display: <%= !@project.document_file_name.blank? ? 'block' : 'none'; %>">
    <% unless @project.document_file_name.nil? %>
      <%= image_tag(icon_for(File.extname(@project.document.url)), style: 'height: 20px') %>&nbsp;
      <%= link_to @project.document_file_name, @project.document.url, target: "_blank" %>&nbsp;
      <% if action == 'edit' %>
        <a href="#" class="project_remove_document" data-id="<%= @project.id %>"><i class="fa fa-remove remove_document"></i></a>
      <% end %>
    <% end %>
  </label>

  <label class="valid_files show_icon_document" style="display: <%= @project.document_file_name.blank? ? 'block' : 'none'; %>">
    Project's Document:
    <%= image_tag(icon_for('docx'), style: 'height: 20px', title: 'Word Document') %>&nbsp;
    <%= image_tag(icon_for('pdf'), style: 'height: 20px', title: 'PDF Document') %>&nbsp;
    <%= image_tag(icon_for('png'), style: 'height: 20px', title: 'Image Document') %>
  </label>
    

  <%= f.file_field :document, class: 'file', data: {'preview-file-type': 'text', 'show-upload': 'false'} %>                  
</div>

<div class="form-group">
  <label>Admin Notes:</label>
  <%= f.cktext_area :notes %>
</div>

<div class="text-right margBtm30">
  <a href="<%= projects_path(locale: I18n.locale) %>" class="btn btn-warning btn-lg long-btn">CANCEL</a>
  <%= f.submit 'SAVE NOW', class: 'btn btn-danger btn-lg long-btn' %>                      
</div>

app/views/projects/edit.html.erb
<% content_for :include_styles do %>
  <%= stylesheet_link_tag "fileinput.min.css" %>
<% end %>

<% content_for :include_scripts do %>
  <%= javascript_include_tag "jquery.dataTables.min.js" %>
  <%= javascript_include_tag "dataTables.bootstrap.min.js" %>
  <%= javascript_include_tag "fileinput.min.js" %>
  <%= javascript_include_tag "modal_confirmation_function.js" %>
<% end %>

<% content_for :page_icon do %>
  <i class="fa fa-edit custom_icon" aria-hidden="true"></i>
<% end %>

<% content_for :body do %>
<div class="row">
    <div class="col-lg-12 pad0">
        <div class="panel panel-default">
            <div class="panel-heading"><strong>Edit Project</strong></div>
            <div class="panel-body">
                <% if @project.errors.any? %>
                    <div class="alert alert-danger custom_alert_notification">
                      <button id="error_alert_x" type="button" class="close"><span aria-hidden="true">&times;</span></button>
                      <strong>There was <%= pluralize(@project.errors.count, "error") %> prohibited this post from being saved:</strong>
                      <div id="errorExplanation">      
                          <% @project.errors.full_messages.each do |msg| %>
                          <p style="display: inline;">* <%= msg %></p><br />
                          <% end %>
                      </div>
                    </div> 
                <% end %>

                <%= form_for(@project, :url => project_path(@project, :locale => I18n.locale), :html => {:class => '', :multipart => true}) do |form_fields| %>
                  <%= render partial: 'projects/projects_form', locals: {f: form_fields, action: 'edit'} %>
                <% end %>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/projects/view_project_applicants.html.erb
<% content_for :include_styles do %>
  <%= stylesheet_link_tag "dataTables.bootstrap.css" %>
  <%= stylesheet_link_tag "dataTables.responsive.min.css" %>  
<% end %>

<% content_for :include_scripts do %>
  <%= javascript_include_tag "jquery.dataTables.min.js" %>
  <%= javascript_include_tag "dataTables.bootstrap.min.js" %>
  <%= javascript_include_tag "dataTables.responsive.min.js" %>
  <%= javascript_include_tag "modal_confirmation_function.js" %>
  <%= javascript_include_tag "search.js" %>
  <%= javascript_include_tag "applicants/make_comments.js" %>
<% end %>

<% content_for :page_icon do %>
  <i class="fa fa-users custom_icon" aria-hidden="true"></i>
<% end %>

<% content_for :body do %>
<input type="hidden" id="project_company_name" value="<%=@project.company_name%>">

<% if session[:role] != 'client' %>
<div class="row">
  <div class="col-lg-12 pad0">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Project Information</strong>            
            <% if can? :edit, Project %>
              <div class="float-left">
                <a href='<%= edit_project_path(@project, locale: I18n.locale) %>' class='white'><i class='fa fa-edit font20' aria-hidden='true'></i></a>&nbsp;&nbsp;
              </div>            
            <% end %>
            <div class="float-right">
              <button type="button" class="btn_collapse" data-toggle="collapse" data-target="#collapse-holder"><i class="glyphicon glyphicon-chevron-up"></i></button>
            </div>
        </div>        
        <div id="collapse-holder" class="panel-body collapse" style="border-color: #d4d4d4;">
            <div class="row">
              <div class="col-md-6">
                  <div class="row">
                    <div class="col-md-12">
                      <ul class="list-unstyled">
                        <li class="row">
                            <div class="col-md-4"><div class="project_applicants_header">Title</div></div>
                            <div class="col-md-8"><%= @project.title %></div>
                        </li>
                        <li class="row">
                            <div class="col-md-4"><div class="project_applicants_header">Company</div></div>
                            <div class="col-md-8"><%= @project.company_name %></div>
                        </li>
                        <li class="row">
                            <div class="col-md-4"><div class="project_applicants_header">Partner</div></div>
                            <div class="col-md-8"><%= @project.partner.try(:fullname) %></div>
                        </li>
                        <li class="row">
                            <div class="col-md-4"><div class="project_applicants_header">Client</div></div>
                            <div class="col-md-8"><%= @project.client.try(:fullname) %></div>
                        </li>
                        <li class="row">
                            <div class="col-md-4"><div class="project_applicants_header">Country</div></div>
                            <div class="col-md-8"><%= @project.country.try(:combine_jp_and_en_name) %></div>
                        </li>
                        <li class="row">
                            <div class="col-md-4"><div class="project_applicants_header">Job Type</div></div>
                            <div class="col-md-8"><%= @project.job_type.try(:combine_jp_and_en_name) %></div>
                        </li>
                        <li class="row">
                            <div class="col-md-4"><div class="project_applicants_header">Assigned Applicants</div></div>
                            <div class="col-md-8">
                              <% @count_associated = @project.count_associated_applicants(session[:role]) %>
                              Registered: <b><%= @count_associated %><b>/</b><%= @project.no_of_needed_applicants %></b>
                              <br>
                              Percentage: <b><%= percent_of(@project.no_of_needed_applicants, @count_associated).to_i %>%</b>
                            </div>
                        </li>
                      </ul>
                    </div>
                    <div class="col-md-12">
                      <div class="row">
                        <div class="col-md-4"><div class="project_applicants_header">File</div></div>
                        <div class="col-md-8">
                          <% unless @project.document_file_name.nil? %>
                            <%= image_tag(icon_for(File.extname(@project.document.url)), style: 'height: 20px') %>&nbsp;
                            <%= link_to @project.document_file_name, @project.document.url, target: "_blank" %>
                          <% else %>
                          -No File-
                          <% end %>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-12">
                        <div class="project_applicants_header">Notes</div>
                        <div><%= raw(@project.notes) %></div>
                    </div>
                  </div>
              </div>            

              <!-- Rigth-Side Descriptions -->
              <div class="col-md-6">
                <div class="project_applicants_header">Description</div>
                <div><%= raw(@project.description) %></div>
              </div>

            </div>
        </div>        
    </div>
  </div>
</div>
<% end %>

<br/>
<br/>

<% if session[:role] == 'client' %><div class="client_home"><a href="/en/projects"><i class="fa fa-home"></i> プロジェクトリストへ戻る / Return To Project List</a></div><% end %>
<%= render partial: 'partial_pages/icons_legend' %>

<!-- Listing of Results -->
<div class="row">
  <div class="col-lg-12 pad0" style="margin-bottom: 100px;">
    <div class="panel panel-default">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-6"><strong><%= session[:role] == 'client' ? '候補者リスト / List of Applicants' : "Resumes Assigned to #{@project.title}" %></strong></div>
            <div class="col-md-6 text-right">
              <div class="pdf_excel_wrapper">
                <a id="generate_pdf" class="pdf_icon_holder" href="#" target="_blank" title="Generate PDF Report">
                  <%= image_tag("/assets/icons/pdf_icon_big.png") %>
                </a>
                &nbsp;
                <% if session[:role] != 'client' %>                
                <a id="generate_excel" class="csv_icon_holder" href="#" target="_blank" title="Generate Excel Report">
                  <%= image_tag("/assets/icons/excel.png") %>
                </a>
                &nbsp;
                <% end %>
              </div>
            </div>
          </div>
        </div>        
        <div class="panel-body">
            <%= render partial: 'search/listing', locals: {applicants: @applicants}  %>
            
            <!-- Modal for Selecting What Report Type & Aptitude test will be shown -->
            <%= render partial: 'search/modal_report_chooser' %>

            <!-- Quick Showing of Comments via Modal -->
            <% if session[:role] == 'client' %>
              <%= render :partial => "partial_pages/show_comments" %>
            <% end %>
        </div>        
    </div>
  </div>
</div>
<% end %>